name: Upload to R2
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Upload-to-R2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: cl-cdn

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install ajv

      - name: Run package script
        run: |
          cd ./cl-cdn
          npm run package

      - name: cleanup
        run: |
          rm -rf ./.git
          rm -rf ./.github
          rm -rf ./.gitignore
          rm -rf ./LICENSE
          rm -rf ./pack.bat
          rm -rf ./start_reindex.bat
          rm -rf ./scripts
          rm -rf ./README.md
          rm -rf ./package.json
          rm -rf ./servers
          cd ./cl-cdn
          
      - uses: ryand56/r2-upload-action@v1.2
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: cl-cdn
          destination-dir: cl-cdn
