name: Upload to R2 Bucket

on:
    push:
        branches:
            - master

    workflow_dispatch:

jobs:
  upload-cdn:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run npm run package
        run: npm run package

      - name: Configure AWS credentials
        run: |
            aws s3 cp ./cdn s3://$BUCKET_NAME --recursive --region $REGION --access-key-id $ACCESS_KEY_ID --secret-access-key $SECRET_ACCESS_KEY
        env:
            ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
            SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
            BUCKET_NAME: skinbook-cdn
            REGION: WEUR
