name: Upload to S3

on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install ajv

      - name: Run validation script
        run: npm run package      

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:

      - name: Upload folder to S3
        run: |
          aws s3 cp cdn s3://test-folder/test --recursive --endpoint-url=https://3709ace193373440a7cb22588c27a53b.r2.cloudflarestorage.com/skinbook-cdn
